sudo: true
dist: bionic
language: python
python:
- '3.8'
branches:
 only:
   - master
env:
  matrix:
  - TOX_ENV=behave
  - TOX_ENV=checkmigrations
  - TOX_ENV=flake8
install:
- sudo apt-get update
- sudo apt-get install libsndfile1
- pip install tox
- mkdir wavs
- cp tests/SuiSiannAdminApp/commands/Oct\ 13\,\ 2018\ _243.wav wavs
script:
- tox -e $TOX_ENV
