sudo: false
language: python
python:
- '3.5'
branches:
#  only:
#    - master
install:
- pip install 'django<2.2'
- pip install -r requirements.txt
- mkdir wavs
- cp tests/SuiSiannAdminApp/commands/Oct\ 13\,\ 2018\ _243.wav wavs
script:
- python manage.py test
- flake8 --exclude venv,__pychache__,.git,csv,wavs --max-line-length 160 ./
#- find csv/ -type f -name '*.csv' -print0 | xargs -0 -n 1 python tool/檢查csv漢羅對齊.py
