sudo: false
language: python
python:
- '3.5'
branches:
#  only:
#    - master
install:
- pip install -r requirements.txt
#script:
#- find csv/ -type f -name '*.csv' -print0 | xargs -0 -n 1 python tool/檢查csv漢羅對齊.py
