version: '3.5'

services:
  admin:
    build: .
    volumes:
      - "./tsu-liāu:/djangoAdmin/tsu-liāu"
      - "./wavs:/djangoAdmin/wavs:ro"
    networks:
      - default
      - nginx-bridge
    expose:
      - 8000
    environment:
       VIRTUAL_HOST: "xn--lhrv4px6k7rz.xn--v0qr21b.xn--kpry57d"
       LETSENCRYPT_HOST: "xn--lhrv4px6k7rz.xn--v0qr21b.xn--kpry57d"
       LETSENCRYPT_EMAIL: "ithuan@xn--v0qr21b.xn--kpry57d"
    restart: always
  it:
    image: kaldi-tuitse_it
    expose:
      - 5000
    volumes:
      - './wavs/:/wav/:ro'
      - kaldis5:/kaldis5
    restart: always
  ji:
    image: kaldi-tuitse_ji
    expose:
      - 5000
    volumes:
      - './wavs/:/wav/:ro'
      - kaldis5:/kaldis5
    restart: always
  sam:
    image: kaldi-tuitse_sam
    expose:
      - 5000
    volumes:
      - kaldis5:/kaldis5
    restart: always

volumes:
  kaldis5:

networks:
  nginx-bridge:
    external: true
