version: '3.5'

services:
  admin:
    build: .
    volumes:
      - "./tsu-liāu:/djangoAdmin/tsu-liāu"
      - "./wavs:/djangoAdmin/wavs:ro"
    networks:
      - default
      - nginx-bridge
    expose:
      - 8000
    environment:
       VIRTUAL_HOST: "xn--lhrv4px6k7rz.xn--v0qr21b.xn--kpry57d"

networks:
  nginx-bridge:
    external: true
