version: '3.5'

services:
  admin:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - "./tsu-liāu:/djangoAdmin/tsu-liāu"
    networks:
      - default
      - nginx-bridge
    expose:
      - 8000
    environment:
       VIRTUAL_HOST: "xn--lhrv4px6k7rz.xn--v0qr21b.xn--kpry57d"
       VIRTUAL_PORT: 8000

networks:
  nginx-bridge:
    external: true
